services:
  - type: web
    name: telegram-osint-bot
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y libjpeg-dev zlib1g-dev
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: GROQ_API_KEY
        sync: false
    plan: free
    autoDeploy: true
